### Tensor 

파이토치의 기본단위 
데이터가 리스트나 어레이로 되어있을 경우 텐서로 변환해야함 

In [2]:
import torch 
import numpy as np 

In [ ]:
x= torch.empty(5,4)
print(x)

In [ ]:
torch.ones(3)

In [3]:
torch.zeros(3)

tensor([0., 0., 0.])

In [9]:
r = np.array([4,56,7])
x= torch.tensor(r)

type(x)
x.size()

torch.Size([3])

In [11]:
y= torch.rand(2,2)
x1 = torch.rand(2,2)

x1+y
torch.add(x1,y)
#y값이 유지되는 덧셈  
y.add(x1)
#더한후 y값 초기화
#언더바는 대체 표현이다. 
y.add_(x)

tensor([[0.5752, 1.0073],
        [0.5258, 0.6946]])

In [13]:
y[1,1]
y[:,1]

tensor([0.7183, 0.3997])

In [14]:
x=torch.rand(8,8)
print(x)

tensor([[0.3725, 0.9307, 0.9546, 0.0903, 0.0268, 0.9923, 0.0481, 0.6587],
        [0.7933, 0.9776, 0.3548, 0.8095, 0.4908, 0.9806, 0.9912, 0.4090],
        [0.8517, 0.3112, 0.9897, 0.1619, 0.9919, 0.0997, 0.4881, 0.0430],
        [0.5855, 0.6494, 0.1726, 0.3849, 0.2014, 0.8049, 0.9551, 0.8161],
        [0.2887, 0.5381, 0.4880, 0.5149, 0.6332, 0.1305, 0.9159, 0.2501],
        [0.8776, 0.9703, 0.2563, 0.9443, 0.2158, 0.7410, 0.2235, 0.1966],
        [0.9458, 0.0124, 0.0515, 0.7846, 0.4196, 0.3257, 0.2014, 0.1426],
        [0.9596, 0.5248, 0.8730, 0.8747, 0.0821, 0.7627, 0.1009, 0.9065]])


In [15]:
x.view(64)

tensor([0.3725, 0.9307, 0.9546, 0.0903, 0.0268, 0.9923, 0.0481, 0.6587, 0.7933,
        0.9776, 0.3548, 0.8095, 0.4908, 0.9806, 0.9912, 0.4090, 0.8517, 0.3112,
        0.9897, 0.1619, 0.9919, 0.0997, 0.4881, 0.0430, 0.5855, 0.6494, 0.1726,
        0.3849, 0.2014, 0.8049, 0.9551, 0.8161, 0.2887, 0.5381, 0.4880, 0.5149,
        0.6332, 0.1305, 0.9159, 0.2501, 0.8776, 0.9703, 0.2563, 0.9443, 0.2158,
        0.7410, 0.2235, 0.1966, 0.9458, 0.0124, 0.0515, 0.7846, 0.4196, 0.3257,
        0.2014, 0.1426, 0.9596, 0.5248, 0.8730, 0.8747, 0.0821, 0.7627, 0.1009,
        0.9065])

In [16]:
x.view(4,16)

tensor([[0.3725, 0.9307, 0.9546, 0.0903, 0.0268, 0.9923, 0.0481, 0.6587, 0.7933,
         0.9776, 0.3548, 0.8095, 0.4908, 0.9806, 0.9912, 0.4090],
        [0.8517, 0.3112, 0.9897, 0.1619, 0.9919, 0.0997, 0.4881, 0.0430, 0.5855,
         0.6494, 0.1726, 0.3849, 0.2014, 0.8049, 0.9551, 0.8161],
        [0.2887, 0.5381, 0.4880, 0.5149, 0.6332, 0.1305, 0.9159, 0.2501, 0.8776,
         0.9703, 0.2563, 0.9443, 0.2158, 0.7410, 0.2235, 0.1966],
        [0.9458, 0.0124, 0.0515, 0.7846, 0.4196, 0.3257, 0.2014, 0.1426, 0.9596,
         0.5248, 0.8730, 0.8747, 0.0821, 0.7627, 0.1009, 0.9065]])

In [18]:
# -1을 넣으면 하나의 값만 정해도 자동으로 들어감 
x.view(-1,4,4)

tensor([[[0.3725, 0.9307, 0.9546, 0.0903],
         [0.0268, 0.9923, 0.0481, 0.6587],
         [0.7933, 0.9776, 0.3548, 0.8095],
         [0.4908, 0.9806, 0.9912, 0.4090]],

        [[0.8517, 0.3112, 0.9897, 0.1619],
         [0.9919, 0.0997, 0.4881, 0.0430],
         [0.5855, 0.6494, 0.1726, 0.3849],
         [0.2014, 0.8049, 0.9551, 0.8161]],

        [[0.2887, 0.5381, 0.4880, 0.5149],
         [0.6332, 0.1305, 0.9159, 0.2501],
         [0.8776, 0.9703, 0.2563, 0.9443],
         [0.2158, 0.7410, 0.2235, 0.1966]],

        [[0.9458, 0.0124, 0.0515, 0.7846],
         [0.4196, 0.3257, 0.2014, 0.1426],
         [0.9596, 0.5248, 0.8730, 0.8747],
         [0.0821, 0.7627, 0.1009, 0.9065]]])

In [19]:
x = torch.ones(1)

In [23]:
x


tensor([1.])

In [22]:
#tensor의 값만 뽑아내고 싶을 경우 
x.item()

1.0